#Archivo YAML. Configura aplicaciones, define servicios o especifica opciones que necesita un progrma para funcionar estructurada de foma ordenada y facil de leer
services:
  - type: web
    name: tunnel-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python tunnel_server.py
    envVars:
      - key: PORT
        value: 10000
